#!/usr/bin/env sh

rm -fR resources/schuleinzugsgebiete/public/vendor
mkdir -p resources/schuleinzugsgebiete/public/vendor

cp node_modules/tachyons/css/tachyons.min.css \
   node_modules/jquery/dist/jquery.min.js \
   node_modules/leaflet/dist/leaflet.css \
   node_modules/leaflet/dist/leaflet.js \
   resources/schuleinzugsgebiete/public/vendor/
